sudo: false
language: php
matrix:
  fast_finish: true
  include:
  - php: 5.6
  - php: 7
    env:
    - EXECUTE_CS_CHECK=true
    - EXECUTE_TEST_COVERALLS=true
  - php: 7.1
  - php: hhvm
  - php: nightly
  allow_failures:
  - php: hhvm
  - php: nightly
before_install:
- if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini ||
  return 0 ; fi
- composer self-update
- if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update
  satooshi/php-coveralls ; fi
install:
- travis_retry composer install --no-interaction --ignore-platform-reqs
script:
- if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpunit -c phpunit.travis.xml
  --coverage-clover clover.xml ; fi
- if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit -c phpunit.travis.xml;
  fi
- if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff
  --dry-run ; fi
after_script:
- if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls ; fi
- if [ $TRAVIS_BRANCH == "master" ] && [ $EXECUTE_TEST_COVERALLS == 'true' ] ; then
  openssl aes-256-cbc -K $encrypted_944d199e46d0_key -iv $encrypted_944d199e46d0_iv
  -in deploy-key.enc -out /home/travis/build/joindin/callingallpapers-api/deploy-key -d; ./vendor/bin/phing deploy; fi
